apiVersion: v1
kind: Pod
metadata:
  name: html
  labels:
    app: html
spec:
  initContainers:
  - name: clone
    image: bitnami/git
    command:
      - git
      - clone
      - https://github.com/kunchalavikram1427/simple-html-page.git
      - /tmp
     volumeMounts:
      - name: scratch
        mountPath: "/tmp"
  containers:
  - name: nginx
    image: nginx:latest
    ports:
     - name: http
       containerport: 80
    volumeMounts:
     - name: scratch
       mountPath: "usr/share/nginx/html"
volume:
  - name: scratch
    emptyDir: {}


---

apiVersion: v1
kind: Service
metadata:
  name: htmlsvc
spec:
  type: NodePort
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000