apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: flask-hello
spec:
  containers:
  - name: flask-container
    image: kunchalavikram/hello-flask:v1
    ports:
    - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-hello
spec:
  selector:
    app: flask-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000


---

apiVersion: v1
kind: Pod
metadata:
  name: greet-pod
  labels:
    app: greet-pod
spec:
  containers:
  - name: flask-container
    image: kunchalavikram/flask-simplegreet:v1
    ports:
    - containerPort: 5000




---

apiVersion: v1
kind: Service
metadata:
  name: flask-greet
spec:
  selector:
    app: flask-greet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000


---

apiVersion: v1
kind: Pod
metadata:
  name: details-pod
  labels:
    app: flask-details
spec:
  containers:
  - name: flask-container
    image: kunchalavikram/flask-simpledetails:v1
    ports:
    - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-details
spec:
  selector:
    app: flask-details
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
