apiVersion: v1
kind: Pod 
metadata : 
  name: sidecar 
  labels : 
    app: nginx 
spec : 
  containers:
  - name: count
    image: busybox:1.28
    args:
    - /bin/sh
    - -c
    - while true;
      do echo This is from 'hostname' on 'date-u' >> /var/log/index/html; sleep 1; done

    volumeMounts: 
     - name: temp 
       mountPath: /var/log 
  - name: application 
    image: nginx:latest 
    ports: 
    - containerPort: 80 
    volumeMounts: 
    - name: temp 
      mountPath: /usr/share/nginx/html 
  volumes: 
  - name: temp 
    emptyDir: {} 

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80k