apiVersion: v1
kind: Pod
metadata:
  name: enviroment-variables-demo
  labels:
    app: env-variables
spec:
  containers:
  - name: debian
    image: debian
    command: ["printenv"]
    args: ["APP_NAME","APP_VERSION"]
    env:
    - name: APP_NAME
      value: "steps_tracker"
    - name: APP_VERSION
      value: "2.1.3" 
  restartPolicy: Never    