apiVersion: v1
kind: Service
metadata:
  name: externalsvc-dns
spec:
  type: ExternalName
  externalName:  clusterip-flask.dev.svc.cluster.local ## put your external url or postgress url.
  #ports:
   # - port: 53
    #  protocol: UDP

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-flask
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - name: http  
      port: 80
      targetPort: 5000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: dev
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: kunchalavikram/hello-flask:v1
        ports:
        - containerPort: 5000