apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config      
      configMap: 
        name: nginx-cm
        items:
        - key: custom-nginx.conf
          path: default.conf

---


apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http  
      port: 8080
      targetPort: 8080
      protocol: TCP
