apiVersion: v1
kind: Pod
metadata:
  name: busy-box1
  labels:
    app: busy-box
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c", "env"]
    envFrom:
    - configMapKeyRef:
         name: app-config
  restartPolicy: Never       