apiVersion: v1
kind: Pod
metadata:
  name: test-pd
  labels:
   app: busybox
   purpose: emptydir-demo
spec:
  containers:
  - image: nginx
    name: test-container1
    command: ["/bin/sh","-C"]
    args: ["date >> /cache/date.txt; sleep 1000"]
  - image: nginx
    name: test-container2
    command: ["/bin/sh","-C"]
    args: ["cat /cache/date.txt; sleep 1000"]    
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
