apiVersion: v1
kind: Pod
metadata:
  name: test-host-pod
spec:
  containers:
  - image: busybox
    name: test-container
    
    command: ["/bin/sh","-C"]
    args: ["date >> /cache/date.txt; sleep 1000"]    
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory